version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-api-whatsApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rplk0ocp329d"
s3_prefix = "cloud-api-whatsApp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
VERIFY_TOKEN = "V7FE6D4ZTy6TnQxpFxiL"