AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-api-whatsApp
  
  Sample SAM Template for cloud-api-whatsApp

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Parameters:
  VerifyToken:
    Type: String

Resources:
  WebhookGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: webhook-get/
      Handler: webhook-get
      Runtime: go1.x
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          VERIFY_TOKEN: !Ref VerifyToken

  WebhookPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: webhook-post/
      Handler: webhook-post
      Runtime: go1.x
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          VERIFY_TOKEN: !Ref VerifyToken
          QUEUE_NAME: !Ref MessageWebhookSqsQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt MessageWebhookSqsQueue.QueueName
  MessageWebhookSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      QueueName: MessageWebhook.fifo
      FifoQueue: true

Outputs:
  WebhookGetAPI:
    Description: "Get - Post"
    Value:  !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"
  WebhookGetFunction:
    Description: "WebhookGetFunction ARN"
    Value: !GetAtt  WebhookGetFunction.Arn
  WebhookGetFunctionIamRole:
    Description: "Implicit IAM Role created for Webhook function"
    Value: !GetAtt WebhookGetFunctionRole.Arn
  WebhookGetToken:
    Description: "Verify Token"
    Value: !Ref VerifyToken

